/*
 * This class was auto-generated from the API references found at
 * https://apireference.connect.worldline-solutions.com/
 */
using Newtonsoft.Json;

namespace Worldline.Connect.Sdk.V1.Domain
{
    public class CreateHostedMandateManagementResponse
    {
        /// <summary>
        /// When the customer is returned to your site we will append this property and value to the query-string. You should store this data, so you can identify the returning customer.
        /// </summary>
        [JsonProperty(PropertyName = "RETURNMAC")]
        public string RETURNMAC { get; set; }

        /// <summary>
        /// This is the ID under which the data for this mandate management can be retrieved.
        /// </summary>
        public string HostedMandateManagementId { get; set; }

        /// <summary>
        /// The partial URL as generated by our system. You will need to add the protocol and the relevant subdomain to this URL, before redirecting your customer to this URL. A special 'payment' subdomain will always work so you can always add 'https://payment.' at the beginning of this response value to view your hosted mandate management pages.
        /// </summary>
        public string PartialRedirectUrl { get; set; }
    }
}
