/*
 * This class was auto-generated from the API references found at
 * https://apireference.connect.worldline-solutions.com/
 */
namespace Worldline.Connect.Sdk.V1.Domain
{
    public class PaymentOperation
    {
        /// <summary>
        /// Object containing amount and ISO currency code attributes
        /// </summary>
        public AmountOfMoney AmountOfMoney { get; set; }

        /// <summary>
        /// A unique identifier of the operation, generated by us.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// <p>Status of the operation. Possible values of a capture operation are:</p>
        /// <list type="bullet">
        ///   <item><description>CREATED</description></item>
        ///   <item><description>REJECTED</description></item>
        ///   <item><description>CANCELLED</description></item>
        ///   <item><description>CAPTURED</description></item>
        ///   <item><description>PAID</description></item>
        ///   <item><description>CHARGEBACKED</description></item>
        ///   <item><description>CHARGEBACK_NOTIFICATION</description></item>
        /// </list>
        /// <p>Possible values of a refund operation are:</p>
        /// <list type="bullet">
        ///   <item><description>CREATED</description></item>
        ///   <item><description>PENDING_CAPTURE</description></item>
        ///   <item><description>REJECTED</description></item>
        ///   <item><description>REFUNDED</description></item>
        /// </list>
        /// </summary>
        public string Status { get; set; }

        /// <summary>
        /// Date and time of the operation.Format: YYYYMMDDHH24MISS
        /// </summary>
        public string Timestamp { get; set; }

        /// <summary>
        /// The type of operation. Possible values are: 
        /// <list type="bullet">
        ///   <item><description>capture</description></item>
        ///   <item><description>refund</description></item>
        /// </list>
        /// </summary>
        public string Type { get; set; }
    }
}
