/*
 * This class was auto-generated from the API references found at
 * https://apireference.connect.worldline-solutions.com/
 */
namespace Worldline.Connect.Sdk.V1.Domain
{
    public class PaymentReferences
    {
        /// <summary>
        /// Your order ID for this transaction that is also returned in our report files
        /// </summary>
        public long? MerchantOrderId { get; set; }

        /// <summary>
        /// Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files.
        /// </summary>
        public string MerchantReference { get; set; }

        /// <summary>
        /// Payment Reference generated by WebCollect
        /// </summary>
        public string PaymentReference { get; set; }

        /// <summary>
        /// Provides an additional means of reconciliation for Gateway merchants
        /// </summary>
        public string ProviderId { get; set; }

        /// <summary>
        /// Provides an additional means of reconciliation, this is the MerchantId used at the provider
        /// </summary>
        public string ProviderMerchantId { get; set; }

        /// <summary>
        /// Provides an additional means of reconciliation for Gateway merchants
        /// </summary>
        public string ProviderReference { get; set; }

        /// <summary>
        /// When you did not supply a merchantReference for your payment, you need to fill this property with the reference of the original payment when you want to refund it
        /// </summary>
        public string ReferenceOrigPayment { get; set; }
    }
}
